[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "OpenAI", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.openai"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.openai"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.openai-native"
version = "@toml.version@"
path = "../native/build/libs/ai.openai-native-@project.version@.jar"
