// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/log;
import ballerina/jballerina.java;
import ballerinax/openai.chat as chat;
import ballerinax/openai.responses as responses;

const DEFAULT_OPENAI_SERVICE_URL = "https://api.openai.com/v1";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# ModelProvider is a client class that provides an interface for interacting with OpenAI Large Language Models.
# Supports both the Chat Completions API (default) and the Responses API, selected via the `apiType` configuration.
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    private final chat:Client? llmClient;
    private final responses:Client? responsesClient;
    private final OPEN_AI_MODEL_NAMES modelType;
    private final ApiType apiType;
    private final decimal? temperature;
    private final int maxTokens;
    private final (ReasoningConfig & readonly)? reasoning;

    # Initializes the OpenAI model with the given connection configuration and model configuration.
    #
    # + apiKey - The OpenAI API key
    # + modelType - The OpenAI model name
    # + serviceUrl - The base URL of OpenAI API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output. Some models may not support this parameter, in which case it will be an error.
    # + reasoning - Reasoning configuration for reasoning-capable models. Applies to both the Chat Completions and Responses APIs
    # + apiType - The OpenAI API endpoint to use; either the Chat Completions API (default) or the Responses API
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} OPEN_AI_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_OPENAI_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = DEFAULT_TEMPERATURE,
            @display {label: "Reasoning Configuration"} ReasoningConfig? reasoning = (),
            @display {label: "API Type"} ApiType apiType = CHAT_COMPLETIONS,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        check validateReasoningConfig(modelType, reasoning);
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.reasoning = reasoning.cloneReadOnly();
        self.apiType = apiType;

        if apiType == CHAT_COMPLETIONS {
            http:ClientHttp1Settings?|error http1Settings = connectionConfig?.http1Settings.cloneWithType();
            if http1Settings is error {
                return error ai:Error("Failed to clone http1Settings", http1Settings);
            }
            chat:ConnectionConfig openAiConfig = {
                auth: {
                    token: apiKey
                },
                httpVersion: connectionConfig.httpVersion,
                http1Settings: http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation
            };
            chat:Client|error llmClient = new (openAiConfig, serviceUrl);
            if llmClient is error {
                return error ai:Error("Failed to initialize OpenAiProvider", llmClient);
            }
            self.llmClient = llmClient;
            self.responsesClient = ();
        } else {
            // Responses API: create a responses:Client (same type as Chat Completions)
            http:ClientHttp1Settings?|error http1Settings = connectionConfig?.http1Settings.cloneWithType();
            if http1Settings is error {
                return error ai:Error("Failed to clone http1Settings", http1Settings);
            }
            responses:ConnectionConfig openAiConfig = {
                auth: {
                    token: apiKey
                },
                httpVersion: connectionConfig.httpVersion,
                http1Settings: http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation
            };
            responses:Client|error responsesApiClient = new (openAiConfig, serviceUrl);
            if responsesApiClient is error {
                return error ai:Error("Failed to initialize Responses Client for Responses API", responsesApiClient);
            }
            self.responsesClient = responsesApiClient;
            self.llmClient = ();
        }
    }

    # Sends a chat request to the OpenAI model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {

        if self.apiType == RESPONSES {
            return self.chatViaResponses(messages, tools, stop);
        }

        return self.chatViaChatCompletions(messages, tools, stop);
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openai.Generator"
    } external;

    // ===== Chat Completions API path (existing implementation) =====

    private isolated function chatViaChatCompletions(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        chat:Client llmClient = <chat:Client>self.llmClient;
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        chat:CreateChatCompletionRequest request = {
            max_completion_tokens: self.maxTokens,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools)
        };
        if temp is decimal {
            request.temperature = temp;
        }
        if stop is string {
            request.stop = stop;
        }
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        if supportsToolCalls && tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }

        ReasoningConfig? reasoningConfig = self.reasoning;
        if reasoningConfig is ReasoningConfig && supportsReasoning(self.modelType) {
            ReasoningEffort? effort = reasoningConfig.effort;
            if effort is ReasoningEffort {
                request.reasoning_effort = effort;
            }
        }

        chat:CreateChatCompletionResponse|error response = llmClient->/chat/completions.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Chat Completion API", err);
            span.close(err);
            return err;
        }

        record {|
            "stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason; 
            int index; 
            chat:ChatCompletionResponseMessage message;
            record {chat:ChatCompletionTokenLogprob[]? content; chat:ChatCompletionTokenLogprob[]? refusal;} logprobs?;
            anydata...;
        |}[] choices = response.choices;
        
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        int? inputTokens = response.usage?.prompt_tokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completion_tokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }
        string? finishReason = response.choices[0].finish_reason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage|ai:Error message = self.convertResponseToAssistantMessage(choices[0].message);
        if message is ai:Error {
            span.close(message);
            return message;
        }
        
        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // ===== Responses API path =====

    private isolated function chatViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        responses:Client responsesClient = <responses:Client>self.responsesClient;
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
            // The Responses API has no stop-sequence parameter, so the value cannot be honored.
            // Failing here is safer than silently letting the model overrun the caller's stop sequence.
            ai:Error err = error ai:Error("The 'stop' parameter is not supported by the Responses API. " +
                    "Use 'apiType = CHAT_COMPLETIONS' if a stop sequence is required.");
            span.close(err);
            return err;
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        // Convert messages to Responses API input format
        [responses:InputParam, string?] [inputItems, instructions] = check convertToResponsesInput(messages, tools, self.modelType);

        responses:CreateResponse request = {
            model: self.modelType,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: false
        };
        
        request.temperature = self.temperature;
        if instructions is string {
            request.instructions = instructions;
        }
        responses:Tool[] allTools = [];
        if tools.length() > 0 {
            responses:FunctionTool[] functionTools = convertToResponsesTools(tools);
            foreach responses:FunctionTool ft in functionTools {
                allTools.push(ft);
            }
            span.addTools(tools);
        }
        if allTools.length() > 0 {
            request.tools = allTools;
        }
        ReasoningConfig? reasoningConfig = self.reasoning;
        if reasoningConfig is ReasoningConfig && supportsReasoning(self.modelType) {
            responses:Reasoning reasoning = {};
            ReasoningEffort? effort = reasoningConfig.effort;
            if effort is ReasoningEffort {
                reasoning.effort = effort;
            }
            request.reasoning = reasoning;
        }

        // POST to /responses
        responses:Response|error response = responsesClient->/responses.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Responses API", err);
            span.close(err);
            return err;
        }

        // Handle non-completed statuses
        string? status = response?.status;
        if status == "failed" {
            string errorMsg = "Response generation failed";
            anydata responseError = response.'error;
            if responseError != () {
                errorMsg = responseError.toString();
            }
            ai:Error err = error ai:LlmConnectionError(errorMsg);
            span.close(err);
            return err;
        }
        if status == "incomplete" {
            string errorMsg = "Response generation incomplete";
            anydata details = response.incomplete_details;
            if details != () {
                errorMsg = string `Response incomplete: ${details.toString()}`;
            }
            ai:Error err = error ai:LlmInvalidResponseError(errorMsg);
            span.close(err);
            return err;
        }
        if status == "cancelled" {
            ai:Error err = error ai:LlmConnectionError("Response generation was cancelled");
            span.close(err);
            return err;
        }
        if status == "in_progress" || status == "queued" {
            ai:Error err = error ai:LlmConnectionError(
                string `Response is still ${status}; use background mode with polling to handle async responses`);
            span.close(err);
            return err;
        }

        // Record observability
        span.addResponseId(response.id);
        responses:ResponseUsage? usage = response.usage;
        if usage is responses:ResponseUsage {
            span.addInputTokenCount(usage.input_tokens);
            span.addOutputTokenCount(usage.output_tokens);
        }
        span.addFinishReason(status ?: "completed");

        // Parse response output into ai:ChatAssistantMessage
        ai:ChatAssistantMessage|ai:Error message = convertResponsesOutputToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // ===== Chat Completions helper methods =====

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns chat:ChatCompletionRequestMessage[]|ai:Error {
        chat:ChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push({
                role: ai:USER,
                content: check getChatMessageStringContent(messages.content),
                name: messages.name
            });
            return chatCompletionRequestMessages;
        }
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatSystemMessage && !supportsToolCalls {
                string reactPrompt = constructReActPrompt(extractToolInfo(tools),
                        check getChatMessageStringContent(message.content));
                chatCompletionRequestMessages.push({role: ai:SYSTEM, content: reactPrompt});
            } else if message is ai:ChatAssistantMessage {
                chat:ChatCompletionRequestAssistantMessage assistantMessage = self.buildRequestAssistantMessage(message);
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatUserMessage {
                chatCompletionRequestMessages.push({
                    role: ai:USER,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatSystemMessage {
                chatCompletionRequestMessages.push({
                    role: ai:SYSTEM,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatFunctionMessage {
                // The tool result must be threaded back as a `tool`-role message carrying the
                // matching `tool_call_id`; otherwise OpenAI rejects the follow-up turn with
                // "An assistant message with 'tool_calls' must be followed by tool messages
                // responding to each 'tool_call_id'". The id fallback mirrors the one used in
                // `buildRequestAssistantMessage` so the response links to the assistant's tool call.
                chatCompletionRequestMessages.push(<chat:ChatCompletionRequestToolMessage>{
                    role: "tool",
                    content: message.content ?: "",
                    tool_call_id: message.id ?: string `call_${message.name}`
                });
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function buildRequestAssistantMessage(ai:ChatAssistantMessage message)
    returns chat:ChatCompletionRequestAssistantMessage {
        chat:ChatCompletionRequestAssistantMessage assistantMessage = {role: ai:ASSISTANT};
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        ai:FunctionCall[]? toolCalls = message.toolCalls;
        if supportsToolCalls && toolCalls is ai:FunctionCall[] {
            assistantMessage.tool_calls = from ai:FunctionCall tc in toolCalls
                select {
                    id: tc.id ?: string `call_${tc.name}`,
                    'type: "function",
                    'function: {
                        name: tc.name,
                        arguments: (tc.arguments ?: {}).toJsonString()
                    }
                };
        } else if !supportsToolCalls && toolCalls is ai:FunctionCall[] {
            assistantMessage.content = formatFunctionCallToJsonWithFences(toolCalls[0]);
        }
        string? content = message?.content;
        if supportsToolCalls && content is string {
            assistantMessage.content = content;
        } else if !supportsToolCalls && content is string {
            assistantMessage.content = formatFinalAnswerToJsonWithFences(content);
        }
        return assistantMessage;
    }

    private isolated function convertResponseToAssistantMessage(chat:ChatCompletionResponseMessage? message)
    returns ai:ChatAssistantMessage|ai:LlmError {
        do {
            boolean hasToolCallResponse = isToolCallSupported(self.modelType);
            ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
            if hasToolCallResponse {
                anydata responseContent = message?.content;
                chatAssistantMessage.content = responseContent is string ? responseContent : ();

                // Use modern tool_calls format (preferred over deprecated function_call)
                chat:ChatCompletionMessageToolCalls? toolCalls = message?.tool_calls;
                if toolCalls is chat:ChatCompletionMessageToolCalls && toolCalls.length() > 0 {
                    ai:FunctionCall[] functionCalls = [];
                    foreach chat:ChatCompletionMessageToolCall|chat:ChatCompletionMessageCustomToolCall tc in toolCalls {
                        if tc is chat:ChatCompletionMessageCustomToolCall {
                            return error ai:LlmError("Custom tools are not supported, Found: " + tc.toJsonString());
                        }
                        chat:ChatCompletionMessageToolCall toolCall = <chat:ChatCompletionMessageToolCall>tc;

                        json arguments = check toolCall.'function.arguments.fromJsonString();
                        functionCalls.push({
                            id: toolCall.id,
                            name: toolCall.'function.name,
                            arguments: check arguments.cloneWithType()
                        });
                    }
                    chatAssistantMessage.toolCalls = functionCalls;
                } else {
                    // Fall back to deprecated function_call for backward compatibility
                    chat:ChatCompletionResponseMessageFunctionCall? functionCall = message?.function_call;
                    if functionCall is chat:ChatCompletionResponseMessageFunctionCall {
                        json arguments = check functionCall.arguments.fromJsonString();
                        chatAssistantMessage.toolCalls = [
                            {
                                name: functionCall.name,
                                arguments: check arguments.cloneWithType()
                            }
                        ];
                    }
                }
                return chatAssistantMessage;
            }

            anydata reActContent = message?.content;
            ai:LlmToolResponse|LlmChatResponse parsedReActResponse = check parseReActLlmResponse(reActContent is string ? reActContent : ());
            if parsedReActResponse is ai:LlmToolResponse {
                chatAssistantMessage.toolCalls = [parsedReActResponse];
                return chatAssistantMessage;
            }
            // Set the "Final Answer" action's input to the chat assistant message content
            chatAssistantMessage.content = parsedReActResponse.content;
            return chatAssistantMessage;
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        json[] result = [];
        foreach ai:ChatMessage msg in messages {
            if msg is ai:ChatUserMessage|ai:ChatSystemMessage {
                result.push(check convertMessageToJson(msg));
            } else {
                result.push(msg);
            }
        }
        return result;
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {
        return {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
    }
    return messages;
}

isolated function convertFunctionsToCompletionTools(ai:ChatCompletionFunctions[] functions) returns chat:ChatCompletionTool[] {
    return from ai:ChatCompletionFunctions fn in functions
        select {
            'type: "function",
            'function: {
                name: fn.name,
                description: fn.description,
                parameters: fn.parameters ?: {}
            }
        };
}

# Models that accept a reasoning parameter (`reasoning_effort` on Chat Completions,
# `reasoning` on the Responses API).
#
# This is an explicit list rather than a name-prefix test: the `gpt-5*-chat-latest` variants share
# the `gpt-5` prefix but are not reasoning models and reject the parameter, and `o1-mini` shares the
# `o1` prefix but does not support it either.
final readonly & map<true> REASONING_MODELS = {
    "o1": true,
    "o1-2024-12-17": true,
    "o1-pro": true,
    "o1-pro-2025-03-19": true,
    "o3": true,
    "o3-mini": true,
    "o3-pro": true,
    "o4-mini": true,
    "codex-mini-latest": true,
    "gpt-5": true,
    "gpt-5-mini": true,
    "gpt-5-nano": true,
    "gpt-5-pro": true,
    "gpt-5-codex": true,
    "gpt-5.1": true,
    "gpt-5.1-codex": true,
    "gpt-5.1-codex-mini": true,
    "gpt-5.1-codex-max": true,
    "gpt-5.2": true,
    "gpt-5.2-pro": true,
    "gpt-5.2-codex": true,
    "gpt-5.3-codex": true,
    "gpt-5.4": true,
    "gpt-5.4-mini": true,
    "gpt-5.4-nano": true,
    "gpt-5.4-pro": true,
    "gpt-5.5": true,
    "gpt-5.5-pro": true,
    "gpt-5.6": true,
    "gpt-5.6-sol": true,
    "gpt-5.6-terra": true,
    "gpt-5.6-luna": true
};

# Reasoning-effort values accepted by each model, as documented in the OpenAI model catalog.
#
# The accepted set differs per model: `minimal` exists only on the `gpt-5` generation, `none` was
# introduced with `gpt-5.1`, `xhigh` with `gpt-5.2`, and the `*-pro` models accept only the higher
# levels. A reasoning model absent from this map does not publish a per-model list, in which case
# the effort is passed through without validation.
final readonly & map<ReasoningEffort[]> SUPPORTED_REASONING_EFFORTS = {
    "gpt-5": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-mini": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-nano": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-pro": [HIGH],
    "gpt-5.1": [NONE, LOW, MEDIUM, HIGH],
    "gpt-5.2": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.2-pro": [MEDIUM, HIGH, XHIGH],
    "gpt-5.3-codex": [LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-mini": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-nano": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-pro": [MEDIUM, HIGH, XHIGH],
    "gpt-5.5": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.5-pro": [MEDIUM, HIGH, XHIGH],
    // The gpt-5.6 family also accepts `max`, which cannot be expressed until the
    // openai.chat/openai.responses connectors regenerate their `ReasoningEffort` union.
    "gpt-5.6": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-sol": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-terra": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-luna": [NONE, LOW, MEDIUM, HIGH, XHIGH]
};

# Determines whether the given model supports the `reasoning` (reasoning_effort) parameter.
#
# + modelType - The model name
# + return - `true` if the model accepts `reasoning`; `false` otherwise
isolated function supportsReasoning(OPEN_AI_MODEL_NAMES modelType) returns boolean =>
    REASONING_MODELS.hasKey(modelType);

# Validates a reasoning configuration against the selected model, so that an unsupported
# combination fails at initialization instead of being rejected by OpenAI at the first call.
#
# + modelType - The model name
# + reasoning - The reasoning configuration to validate, if any
# + return - An `ai:Error` if the configuration is not valid for the model; otherwise `()`
isolated function validateReasoningConfig(OPEN_AI_MODEL_NAMES modelType, ReasoningConfig? reasoning) returns ai:Error? {
    if reasoning !is ReasoningConfig {
        return;
    }
    if !supportsReasoning(modelType) {
        return error ai:Error(string `The model '${modelType}' does not support the 'reasoning' configuration.`);
    }
    ReasoningEffort? effort = reasoning.effort;
    if effort !is ReasoningEffort {
        return;
    }
    ReasoningEffort[]? supportedEfforts = SUPPORTED_REASONING_EFFORTS[modelType];
    if supportedEfforts is ReasoningEffort[] && supportedEfforts.indexOf(effort) is () {
        return error ai:Error(string `The model '${modelType}' does not support the reasoning effort '${
                effort}'. Supported values: ${string:'join(", ", ...supportedEfforts)}.`);
    }
    return;
}
