// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/log;
import ballerina/jballerina.java;
import ballerinax/openai.chat;
import ballerinax/openai.responses;

const DEFAULT_OPENAI_SERVICE_URL = "https://api.openai.com/v1";
const DEFAULT_MAX_TOKEN_COUNT = 4096;

# ModelProvider is a client class that provides an interface for interacting with OpenAI Large Language Models.
# Supports both the Chat Completions API (default) and the Responses API, selected via the `apiType` configuration.
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    private final chat:Client? llmClient;
    private final responses:Client? responsesClient;
    // Raw HTTP client for the streaming endpoint of whichever API `apiType` selects; the
    // generated `chat:Client`/`responses:Client` cannot consume Server-Sent Events.
    private final http:Client? streamClient;
    private final OPEN_AI_MODEL_NAMES modelType;
    private final ApiType apiType;
    private final decimal? temperature;
    private final int maxTokens;
    private final ReasoningEffort? reasoning;

    # Initializes the OpenAI model with the given connection configuration and model configuration.
    #
    # + apiKey - The OpenAI API key
    # + modelType - The OpenAI model name
    # + serviceUrl - The base URL of OpenAI API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output. Some models do not
    #                 support this parameter, in which case supplying it results in an error
    # + reasoningEffort - Reasoning effort level for reasoning-capable models. Applies to both the Chat Completions
    #                  (`reasoning_effort`) and the Responses (`reasoning.effort`) APIs
    # + apiType - The OpenAI API endpoint to use; either the Chat Completions API (default) or the Responses API
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} OPEN_AI_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_OPENAI_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal? temperature = (),
            @display {label: "Reasoning Effort"} ReasoningEffort? reasoningEffort = (),
            @display {label: "API Type"} ApiType apiType = CHAT_COMPLETIONS,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        check validateReasoningEffort(modelType, reasoningEffort);
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.reasoning = reasoningEffort;
        self.apiType = apiType;

        if apiType == CHAT_COMPLETIONS {
            http:ClientHttp1Settings?|error http1Settings = connectionConfig?.http1Settings.cloneWithType();
            if http1Settings is error {
                return error ai:Error("Failed to clone http1Settings", http1Settings);
            }
            chat:ConnectionConfig openAiConfig = {
                auth: {
                    token: apiKey
                },
                httpVersion: connectionConfig.httpVersion,
                http1Settings: http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation
            };
            chat:Client|error llmClient = new (openAiConfig, serviceUrl);
            if llmClient is error {
                return error ai:Error("Failed to initialize OpenAiProvider", llmClient);
            }
            // Raw HTTP client for streaming (SSE), which the generated chat:Client cannot do.
            self.llmClient = llmClient;
            self.responsesClient = ();
            self.streamClient = check initStreamClient(apiKey, serviceUrl, connectionConfig);
        } else {
            // Responses API: create a responses:Client (same type as Chat Completions)
            http:ClientHttp1Settings?|error http1Settings = connectionConfig?.http1Settings.cloneWithType();
            if http1Settings is error {
                return error ai:Error("Failed to clone http1Settings", http1Settings);
            }
            responses:ConnectionConfig openAiConfig = {
                auth: {
                    token: apiKey
                },
                httpVersion: connectionConfig.httpVersion,
                http1Settings: http1Settings ?: {},
                http2Settings: connectionConfig.http2Settings ?: {},
                timeout: connectionConfig.timeout,
                forwarded: connectionConfig.forwarded,
                poolConfig: connectionConfig.poolConfig,
                cache: connectionConfig.cache ?: {},
                compression: connectionConfig.compression,
                circuitBreaker: connectionConfig.circuitBreaker,
                retryConfig: connectionConfig.retryConfig,
                responseLimits: connectionConfig.responseLimits ?: {},
                secureSocket: connectionConfig.secureSocket,
                proxy: connectionConfig.proxy,
                validation: connectionConfig.validation
            };
            responses:Client|error responsesApiClient = new (openAiConfig, serviceUrl);
            if responsesApiClient is error {
                return error ai:Error("Failed to initialize Responses Client for Responses API", responsesApiClient);
            }
            // Raw HTTP client for streaming (SSE) against the /responses endpoint.
            self.responsesClient = responsesApiClient;
            self.llmClient = ();
            self.streamClient = check initStreamClient(apiKey, serviceUrl, connectionConfig);
        }
    }

    # Sends a chat request to the OpenAI model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        if self.apiType == RESPONSES {
            return self.chatViaResponses(messages, tools, stop);
        }

        return self.chatViaChatCompletions(messages, tools, stop);
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
            returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openai.Generator"
    } external;

    // ===== Chat Completions API path (existing implementation) =====

    private isolated function chatViaChatCompletions(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        chat:Client llmClient = <chat:Client>self.llmClient;
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        chat:CreateChatCompletionRequest request = {
            max_completion_tokens: self.maxTokens,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools)
        };
        if temp is decimal {
            request.temperature = temp;
        }
        if stop is string {
            request.stop = stop;
        }
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        if supportsToolCalls && tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }

        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort && supportsReasoning(self.modelType) {
            request.reasoning_effort = reasoningEffort;
        }

        chat:CreateChatCompletionResponse|error response = llmClient->/chat/completions.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Chat Completion API", err);
            span.close(err);
            return err;
        }

        record {|
            "stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason; 
            int index; 
            chat:ChatCompletionResponseMessage message;
            record {chat:ChatCompletionTokenLogprob[]? content; chat:ChatCompletionTokenLogprob[]? refusal;} logprobs?;
            anydata...;
        |}[] choices = response.choices;
        
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        int? inputTokens = response.usage?.prompt_tokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completion_tokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }
        span.addFinishReason(choices[0].finish_reason);

        ai:ChatAssistantMessage|ai:Error message = self.convertResponseToAssistantMessage(choices[0].message);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a streaming chat request to the OpenAI model with the given messages and tools.
    # Streams via the Chat Completions API or the Responses API, selected by `apiType`.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - A stream of chat completion chunks, or an error in case of failures
    isolated remote function chatStream(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools = [], string? stop = ())
            returns stream<ai:ChatCompletionChunk, ai:Error?>|ai:Error {
        if self.apiType == RESPONSES {
            return self.chatStreamViaResponses(messages, tools, stop);
        }
        http:Client? streamClient = self.streamClient;
        if streamClient is () {
            return error ai:Error("Streaming client is not initialized.");
        }
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        chat:ChatCompletionRequestMessage[]|ai:Error requestMessages =
            self.prepareCompletionRequestMessages(messages, tools);
        if requestMessages is ai:Error {
            span.close(requestMessages);
            return requestMessages;
        }
        chat:CreateChatCompletionRequest request = {
            max_completion_tokens: self.maxTokens,
            model: self.modelType,
            messages: requestMessages,
            'stream: true,
            stream_options: {include_usage: true}
        };
        if temp is decimal {
            request.temperature = temp;
        }
        if stop is string {
            request.stop = stop;
        }
        if isToolCallSupported(self.modelType) && tools.length() > 0 {
            request.tools = convertFunctionsToCompletionTools(tools);
            span.addTools(tools);
        }
        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort && supportsReasoning(self.modelType) {
            request.reasoning_effort = reasoningEffort;
        }

        stream<http:SseEvent, error?>|ai:Error sseStream = openSseStream(streamClient, "/chat/completions", request);
        if sseStream is ai:Error {
            span.close(sseStream);
            return sseStream;
        }
        stream<ai:ChatCompletionChunk, ai:Error?> chunkStream = new (new OpenAiChunkIterator(sseStream, span));
        return chunkStream;
    }

    // Streaming via the Responses API: builds the /responses request with stream:true,
    // opens the SSE stream, and maps the Responses events onto ai:ChatCompletionChunk.
    private isolated function chatStreamViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop)
            returns stream<ai:ChatCompletionChunk, ai:Error?>|ai:Error {
        http:Client? streamClient = self.streamClient;
        if streamClient is () {
            return error ai:Error("Streaming client is not initialized.");
        }
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
            ai:Error err = error ai:Error("The 'stop' parameter is not supported by the Responses API. " +
                    "Use 'apiType = CHAT_COMPLETIONS' if a stop sequence is required.");
            span.close(err);
            return err;
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        [responses:InputParam, string?]|ai:Error converted =
            convertToResponsesInput(messages, tools, self.modelType);
        if converted is ai:Error {
            span.close(converted);
            return converted;
        }
        [responses:InputParam, string?] [inputItems, instructions] = converted;
        responses:CreateResponse request = {
            model: self.modelType,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: false,
            'stream: true
        };
        if temp is decimal {
            request.temperature = temp;
        }
        if instructions is string {
            request.instructions = instructions;
        }
        // The Responses API has no per-model tool-call gate of its own: the models without
        // native tool calls are driven through the ReAct prompt that `convertToResponsesInput`
        // folds into `instructions`, so the tools must not also be declared on the request.
        if isToolCallSupported(self.modelType) && tools.length() > 0 {
            responses:Tool[] allTools = [];
            foreach responses:FunctionTool ft in convertToResponsesTools(tools) {
                allTools.push(ft);
            }
            request.tools = allTools;
            span.addTools(tools);
        }
        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort && supportsReasoning(self.modelType) {
            // Ask for a reasoning summary so the reasoning_summary_text.delta events stream;
            // without it the model's thinking is not surfaced. Only the streaming path asks:
            // `ai:ChatCompletionChunkDelta` has a `reasoning` field to carry the fragments,
            // whereas `ai:ChatAssistantMessage` - what `chat()` returns - has nowhere to put a
            // summary, so requesting one there would only pay for output nobody can read.
            request.reasoning = {effort: reasoningEffort, summary: "auto"};
        }

        stream<http:SseEvent, error?>|ai:Error sseStream = openSseStream(streamClient, "/responses", request);
        if sseStream is ai:Error {
            span.close(sseStream);
            return sseStream;
        }
        stream<ai:ChatCompletionChunk, ai:Error?> chunkStream = new (new ResponsesChunkIterator(sseStream, span));
        return chunkStream;
    }

    // ===== Responses API path =====

    private isolated function chatViaResponses(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns ai:ChatAssistantMessage|ai:Error {
        responses:Client responsesClient = <responses:Client>self.responsesClient;
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openai");
        if stop is string {
            span.addStopSequence(stop);
            // The Responses API has no stop-sequence parameter, so the value cannot be honored.
            // Failing here is safer than silently letting the model overrun the caller's stop sequence.
            ai:Error err = error ai:Error("The 'stop' parameter is not supported by the Responses API. " +
                    "Use 'apiType = CHAT_COMPLETIONS' if a stop sequence is required.");
            span.close(err);
            return err;
        }
        decimal? temp = self.temperature;
        if temp is decimal {
            span.addTemperature(temp);
        }
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        // Convert messages to Responses API input format
        [responses:InputParam, string?] [inputItems, instructions] =
            check convertToResponsesInput(messages, tools, self.modelType);

        responses:CreateResponse request = {
            model: self.modelType,
            input: inputItems,
            max_output_tokens: self.maxTokens,
            store: false
        };
        if temp is decimal {
            request.temperature = temp;
        }
        if instructions is string {
            request.instructions = instructions;
        }
        // Models without native tool calls are driven through the ReAct prompt that
        // `convertToResponsesInput` folds into `instructions`, so the tools must not also be
        // declared on the request.
        responses:Tool[] allTools = [];
        if isToolCallSupported(self.modelType) && tools.length() > 0 {
            responses:FunctionTool[] functionTools = convertToResponsesTools(tools);
            foreach responses:FunctionTool ft in functionTools {
                allTools.push(ft);
            }
            span.addTools(tools);
        }
        if allTools.length() > 0 {
            request.tools = allTools;
        }
        ReasoningEffort? reasoningEffort = self.reasoning;
        if reasoningEffort is ReasoningEffort && supportsReasoning(self.modelType) {
            request.reasoning = {effort: reasoningEffort};
        }

        // POST to /responses
        responses:Response|error response = responsesClient->/responses.post(request);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            log:printError("Error response received from Responses API", err);
            span.close(err);
            return err;
        }

        // Handle non-completed statuses
        ai:Error? statusError = checkResponseStatus(response);
        if statusError is ai:Error {
            span.close(statusError);
            return statusError;
        }

        // Record observability
        span.addResponseId(response.id);
        responses:ResponseUsage? usage = response.usage;
        if usage is responses:ResponseUsage {
            span.addInputTokenCount(usage.input_tokens);
            span.addOutputTokenCount(usage.output_tokens);
        }
        span.addFinishReason(response?.status ?: "completed");

        // Parse response output into ai:ChatAssistantMessage
        ai:ChatAssistantMessage|ai:Error message = convertResponsesOutputToAssistantMessage(response);
        if message is ai:Error {
            span.close(message);
            return message;
        }

        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    // ===== Chat Completions helper methods =====

    # Sends a streaming chat request to the model using the given prompt and streams
    # back the generated answer. Only `string` is supported as the expected type.
    #
    # + prompt - The prompt to use in the chat request
    # + td - The expected type of the streamed value; must be `string`
    # + return - A stream of the generated value, or an error if the type is unsupported
    remote function generateStream(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>)
            returns stream<td, ai:Error?>|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openai.StreamGenerator"
    } external;

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns chat:ChatCompletionRequestMessage[]|ai:Error {
        chat:ChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push({
                role: ai:USER,
                content: check getChatMessageStringContent(messages.content),
                name: messages.name
            });
            return chatCompletionRequestMessages;
        }
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        // Pairs each tool result with the assistant tool call it answers when the caller's
        // messages carry no ids of their own.
        ToolCallIdRegistry registry = {};
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatSystemMessage && !supportsToolCalls {
                string reactPrompt = constructReActPrompt(extractToolInfo(tools),
                        check getChatMessageStringContent(message.content));
                chatCompletionRequestMessages.push({role: ai:SYSTEM, content: reactPrompt});
            } else if message is ai:ChatAssistantMessage {
                chat:ChatCompletionRequestAssistantMessage assistantMessage =
                    self.buildRequestAssistantMessage(message, registry);
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatUserMessage {
                chatCompletionRequestMessages.push({
                    role: ai:USER,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatSystemMessage {
                chatCompletionRequestMessages.push({
                    role: ai:SYSTEM,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatFunctionMessage {
                if !supportsToolCalls {
                    // ReAct path: the assistant turn carries JSON-fenced content and no `tool_calls`,
                    // so a `tool`-role message would have nothing to answer and OpenAI would reject
                    // the turn. Thread the observation back on the legacy `function` role instead.
                    chatCompletionRequestMessages.push(<chat:ChatCompletionRequestFunctionMessage>{
                        role: "function",
                        content: message.content,
                        name: message.name
                    });
                    continue;
                }
                // The tool result must be threaded back as a `tool`-role message carrying the
                // matching `tool_call_id`; otherwise OpenAI rejects the follow-up turn with
                // "An assistant message with 'tool_calls' must be followed by tool messages
                // responding to each 'tool_call_id'".
                chatCompletionRequestMessages.push(<chat:ChatCompletionRequestToolMessage>{
                    role: "tool",
                    content: message.content ?: "",
                    tool_call_id: claimToolCallId(message.name, message.id, registry)
                });
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function buildRequestAssistantMessage(ai:ChatAssistantMessage message,
            ToolCallIdRegistry registry) returns chat:ChatCompletionRequestAssistantMessage {
        chat:ChatCompletionRequestAssistantMessage assistantMessage = {role: ai:ASSISTANT};
        boolean supportsToolCalls = isToolCallSupported(self.modelType);
        ai:FunctionCall[]? toolCalls = message.toolCalls;
        if supportsToolCalls && toolCalls is ai:FunctionCall[] {
            chat:ChatCompletionMessageToolCall[] requestToolCalls = [];
            foreach ai:FunctionCall tc in toolCalls {
                requestToolCalls.push({
                    id: issueToolCallId(tc.name, tc.id, registry),
                    'type: "function",
                    'function: {
                        name: tc.name,
                        arguments: (tc.arguments ?: {}).toJsonString()
                    }
                });
            }
            assistantMessage.tool_calls = requestToolCalls;
        } else if !supportsToolCalls && toolCalls is ai:FunctionCall[] {
            assistantMessage.content = formatFunctionCallToJsonWithFences(toolCalls[0]);
        }
        string? content = message?.content;
        if supportsToolCalls && content is string {
            assistantMessage.content = content;
        } else if !supportsToolCalls && content is string {
            assistantMessage.content = formatFinalAnswerToJsonWithFences(content);
        }
        return assistantMessage;
    }

    private isolated function convertResponseToAssistantMessage(chat:ChatCompletionResponseMessage? message)
    returns ai:ChatAssistantMessage|ai:LlmError {
        do {
            boolean hasToolCallResponse = isToolCallSupported(self.modelType);
            ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
            if hasToolCallResponse {
                anydata responseContent = message?.content;
                chatAssistantMessage.content = responseContent is string ? responseContent : ();

                // Use modern tool_calls format (preferred over deprecated function_call)
                chat:ChatCompletionMessageToolCalls? toolCalls = message?.tool_calls;
                if toolCalls is chat:ChatCompletionMessageToolCalls && toolCalls.length() > 0 {
                    ai:FunctionCall[] functionCalls = [];
                    foreach chat:ChatCompletionMessageToolCall|chat:ChatCompletionMessageCustomToolCall tc
                            in toolCalls {
                        if tc is chat:ChatCompletionMessageCustomToolCall {
                            return error ai:LlmError("Custom tools are not supported, Found: " + tc.toJsonString());
                        }
                        chat:ChatCompletionMessageToolCall toolCall = <chat:ChatCompletionMessageToolCall>tc;

                        json arguments = check toolCall.'function.arguments.fromJsonString();
                        functionCalls.push({
                            id: toolCall.id,
                            name: toolCall.'function.name,
                            arguments: check arguments.cloneWithType()
                        });
                    }
                    chatAssistantMessage.toolCalls = functionCalls;
                } else {
                    // Fall back to deprecated function_call for backward compatibility
                    chat:ChatCompletionResponseMessageFunctionCall? functionCall = message?.function_call;
                    if functionCall is chat:ChatCompletionResponseMessageFunctionCall {
                        json arguments = check functionCall.arguments.fromJsonString();
                        chatAssistantMessage.toolCalls = [
                            {
                                name: functionCall.name,
                                arguments: check arguments.cloneWithType()
                            }
                        ];
                    }
                }
                return chatAssistantMessage;
            }

            anydata reActContent = message?.content;
            ai:LlmToolResponse|LlmChatResponse parsedReActResponse =
                check parseReActLlmResponse(reActContent is string ? reActContent : ());
            if parsedReActResponse is ai:LlmToolResponse {
                chatAssistantMessage.toolCalls = [parsedReActResponse];
                return chatAssistantMessage;
            }
            // Set the "Final Answer" action's input to the chat assistant message content
            chatAssistantMessage.content = parsedReActResponse.content;
            return chatAssistantMessage;
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

# Bookkeeping that pairs each tool result with the assistant tool call it answers when the
# caller's messages carry no ids of their own.
type ToolCallIdRegistry record {|
    # Per-tool-name occurrence counters, used to synthesize ids
    map<int> counts = {};
    # The ids assigned to the assistant's calls, in order, per tool name
    map<string[]> issued = {};
    # How many results have already claimed an issued id, per tool name
    map<int> claimed = {};
|};

# Records the id of an assistant tool call, synthesizing one when the call carries none.
#
# OpenAI requires every assistant `tool_calls` entry to have an id that is unique within the request
# and to be answered by a result carrying the same id. Falling back to the tool name alone collides
# whenever the same tool is called more than once in a turn, so the occurrence index is appended.
#
# + name - The tool name
# + id - The id the call already carries, if any
# + registry - The registry, updated in place
# + return - The id to send for this call
isolated function issueToolCallId(string name, string? id, ToolCallIdRegistry registry) returns string {
    string toolCallId = id ?: synthesizeToolCallId(name, registry);
    string[] issued = registry.issued[name] ?: [];
    issued.push(toolCallId);
    registry.issued[name] = issued;
    return toolCallId;
}

# Resolves the `tool_call_id` for a tool result: the id it carries, or the id of the next
# assistant call to that tool that no result has claimed yet.
#
# Pairing has to go through the ids actually issued rather than a second independent counter.
# A counter that only advances on the messages *without* an id drifts out of step the moment
# one side of a call/result pair carries a real id and the other does not, and the result then
# answers a `tool_call_id` that appears nowhere in the request.
#
# + name - The tool name
# + id - The id the result already carries, if any
# + registry - The registry, updated in place
# + return - The `tool_call_id` to send for this result
isolated function claimToolCallId(string name, string? id, ToolCallIdRegistry registry) returns string {
    string[] issued = registry.issued[name] ?: [];
    int claimed = registry.claimed[name] ?: 0;
    if id is string {
        // Keep the pointer in step when the result names the call it answers.
        if claimed < issued.length() && issued[claimed] == id {
            registry.claimed[name] = claimed + 1;
        }
        return id;
    }
    if claimed < issued.length() {
        registry.claimed[name] = claimed + 1;
        return issued[claimed];
    }
    // No unanswered call to pair with - a result arriving without one is malformed, but
    // synthesizing keeps the id unique instead of colliding on the bare tool name.
    return synthesizeToolCallId(name, registry);
}

# Synthesizes a tool call id that is unique per occurrence of the given tool name.
#
# + name - The tool name
# + registry - The registry, whose per-name counter is updated in place
# + return - The generated id
isolated function synthesizeToolCallId(string name, ToolCallIdRegistry registry) returns string {
    int occurrence = (registry.counts[name] ?: 0) + 1;
    registry.counts[name] = occurrence;
    return string `call_${name}_${occurrence}`;
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        json[] result = [];
        foreach ai:ChatMessage msg in messages {
            if msg is ai:ChatUserMessage|ai:ChatSystemMessage {
                result.push(check convertMessageToJson(msg));
            } else {
                result.push(msg);
            }
        }
        return result;
    }
    if messages is ai:ChatUserMessage|ai:ChatSystemMessage {
        return {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
    }
    return messages;
}

isolated function convertFunctionsToCompletionTools(ai:ChatCompletionFunctions[] functions)
        returns chat:ChatCompletionTool[] {
    return from ai:ChatCompletionFunctions fn in functions
        select {
            'type: "function",
            'function: {
                name: fn.name,
                description: fn.description,
                parameters: fn.parameters ?: {}
            }
        };
}

# Models that accept a reasoning parameter (`reasoning_effort` on Chat Completions,
# `reasoning` on the Responses API).
#
# This is an explicit list rather than a name-prefix test: the `gpt-5*-chat-latest` variants share
# the `gpt-5` prefix but are not reasoning models and reject the parameter, and `o1-mini` shares the
# `o1` prefix but does not support it either.
final readonly & map<true> REASONING_MODELS = {
    "o1": true,
    "o1-2024-12-17": true,
    "o1-pro": true,
    "o1-pro-2025-03-19": true,
    "o3": true,
    "o3-mini": true,
    "o3-pro": true,
    "o4-mini": true,
    "codex-mini-latest": true,
    "gpt-5": true,
    "gpt-5-mini": true,
    "gpt-5-nano": true,
    "gpt-5-pro": true,
    "gpt-5-codex": true,
    "gpt-5.1": true,
    "gpt-5.1-codex": true,
    "gpt-5.1-codex-mini": true,
    "gpt-5.1-codex-max": true,
    "gpt-5.2": true,
    "gpt-5.2-pro": true,
    "gpt-5.2-codex": true,
    "gpt-5.3-codex": true,
    "gpt-5.4": true,
    "gpt-5.4-mini": true,
    "gpt-5.4-nano": true,
    "gpt-5.4-pro": true,
    "gpt-5.5": true,
    "gpt-5.5-pro": true,
    "gpt-5.6": true,
    "gpt-5.6-sol": true,
    "gpt-5.6-terra": true,
    "gpt-5.6-luna": true
};

# Reasoning-effort values accepted by each model, as documented in the OpenAI model catalog.
#
# The accepted set differs per model: `minimal` exists only on the `gpt-5` generation, `none` was
# introduced with `gpt-5.1`, `xhigh` with `gpt-5.2`, and the `*-pro` models accept only the higher
# levels. A reasoning model absent from this map does not publish a per-model list, in which case
# the effort is passed through without validation.
final readonly & map<ReasoningEffort[]> SUPPORTED_REASONING_EFFORTS = {
    "gpt-5": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-mini": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-nano": [MINIMAL, LOW, MEDIUM, HIGH],
    "gpt-5-pro": [HIGH],
    "gpt-5.1": [NONE, LOW, MEDIUM, HIGH],
    "gpt-5.2": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.2-pro": [MEDIUM, HIGH, XHIGH],
    "gpt-5.3-codex": [LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-mini": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-nano": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.4-pro": [MEDIUM, HIGH, XHIGH],
    "gpt-5.5": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.5-pro": [MEDIUM, HIGH, XHIGH],
    // The gpt-5.6 family also accepts `max`, which cannot be expressed until the
    // openai.chat/openai.responses connectors regenerate their `ReasoningEffort` union.
    "gpt-5.6": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-sol": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-terra": [NONE, LOW, MEDIUM, HIGH, XHIGH],
    "gpt-5.6-luna": [NONE, LOW, MEDIUM, HIGH, XHIGH]
};

# Determines whether the given model supports the `reasoning` (reasoning_effort) parameter.
#
# + modelType - The model name
# + return - `true` if the model accepts `reasoning`; `false` otherwise
isolated function supportsReasoning(OPEN_AI_MODEL_NAMES modelType) returns boolean =>
    REASONING_MODELS.hasKey(modelType);

# Validates a reasoning effort against the selected model, so that an unsupported
# combination fails at initialization instead of being rejected by OpenAI at the first call.
#
# + modelType - The model name
# + effort - The reasoning effort to validate, if any
# + return - An `ai:Error` if the effort is not valid for the model; otherwise `()`
isolated function validateReasoningEffort(OPEN_AI_MODEL_NAMES modelType, ReasoningEffort? effort) returns ai:Error? {
    if effort !is ReasoningEffort {
        return;
    }
    if !supportsReasoning(modelType) {
        return error ai:Error(string `The model '${modelType}' does not support the 'reasoningEffort' configuration.`);
    }
    ReasoningEffort[]? supportedEfforts = SUPPORTED_REASONING_EFFORTS[modelType];
    if supportedEfforts is ReasoningEffort[] && supportedEfforts.indexOf(effort) is () {
        return error ai:Error(string `The model '${modelType}' does not support the reasoning effort '${
                effort}'. Supported values: ${string:'join(", ", ...supportedEfforts)}.`);
    }
    return;
}

# Builds the raw `http:Client` used for the streaming endpoints, which the generated
# `chat:Client`/`responses:Client` cannot drive because they cannot consume Server-Sent
# Events.
#
# The caller's whole `ConnectionConfig` is carried over, so a deployment that reaches
# OpenAI through a proxy or a private truststore streams under exactly the settings its
# non-streaming calls already use - otherwise `chat` would work and `chatStream` would fail
# on the same configuration.
#
# + apiKey - The OpenAI API key
# + serviceUrl - The base URL of the OpenAI API endpoint
# + connectionConfig - The caller's connection configuration
# + return - The streaming client, or an `ai:Error` if it cannot be initialized
isolated function initStreamClient(string apiKey, string serviceUrl, ConnectionConfig connectionConfig)
        returns http:Client|ai:Error {
    http:ClientConfiguration streamConfig = {
        auth: {token: apiKey},
        httpVersion: connectionConfig.httpVersion,
        http1Settings: connectionConfig.http1Settings ?: {},
        http2Settings: connectionConfig.http2Settings ?: {},
        timeout: connectionConfig.timeout,
        forwarded: connectionConfig.forwarded,
        cache: connectionConfig.cache ?: {},
        compression: connectionConfig.compression,
        responseLimits: connectionConfig.responseLimits ?: {},
        validation: connectionConfig.validation
    };
    http:PoolConfiguration? poolConfig = connectionConfig.poolConfig;
    if poolConfig is http:PoolConfiguration {
        streamConfig.poolConfig = poolConfig;
    }
    http:CircuitBreakerConfig? circuitBreaker = connectionConfig.circuitBreaker;
    if circuitBreaker is http:CircuitBreakerConfig {
        streamConfig.circuitBreaker = circuitBreaker;
    }
    http:RetryConfig? retryConfig = connectionConfig.retryConfig;
    if retryConfig is http:RetryConfig {
        streamConfig.retryConfig = retryConfig;
    }
    http:ClientSecureSocket? secureSocket = connectionConfig.secureSocket;
    if secureSocket is http:ClientSecureSocket {
        streamConfig.secureSocket = secureSocket;
    }
    http:ProxyConfig? proxy = connectionConfig.proxy;
    if proxy is http:ProxyConfig {
        streamConfig.proxy = proxy;
    }
    http:Client|error streamClient = new (serviceUrl, streamConfig);
    if streamClient is error {
        return error ai:Error("Failed to initialize the OpenAI streaming client", streamClient);
    }
    return streamClient;
}

# Sends a streaming request and opens the Server-Sent Events stream it answers with.
#
# The POST binds to `http:Response` because the payload has to be read as an event stream
# rather than data-bound, and that also switches off the client's status-code error
# mapping - so the status is checked here. Without it OpenAI's own message for an expired
# key, a rate limit, or a rejected parameter is discarded and the caller is told only that
# the stream could not be opened.
#
# + streamClient - The raw HTTP client for the streaming endpoint
# + path - The endpoint path to post to
# + request - The request payload
# + return - The SSE event stream, or an `ai:Error` describing the failure
isolated function openSseStream(http:Client streamClient, string path, anydata request)
        returns stream<http:SseEvent, error?>|ai:Error {
    http:Response|error response = streamClient->post(path, request);
    if response is error {
        return error ai:LlmConnectionError("Error while connecting to the model for streaming", response);
    }
    int statusCode = response.statusCode;
    if statusCode < 200 || statusCode >= 300 {
        string? detail = extractHttpErrorDetail(response);
        string message = detail is string
            ? string `The model rejected the streaming request with status ${statusCode}: ${detail}`
            : string `The model rejected the streaming request with status ${statusCode}`;
        return error ai:LlmConnectionError(message);
    }
    stream<http:SseEvent, error?>|error sseStream = response.getSseEventStream();
    if sseStream is error {
        return error ai:LlmConnectionError("Failed to open the SSE stream from the model", sseStream);
    }
    return sseStream;
}

# Pulls the human-readable detail out of a non-2xx streaming response, which carries the
# usual OpenAI `{"error": {"message": ...}}` body rather than an event stream.
#
# + response - The non-2xx response
# + return - The failure detail, or `()` when the body carries none
isolated function extractHttpErrorDetail(http:Response response) returns string? {
    json|error payload = response.getJsonPayload();
    if payload is error {
        string|error text = response.getTextPayload();
        if text is string && text.trim() != "" {
            return text.trim();
        }
        return ();
    }
    string? frameMessage = extractStreamErrorFrame(payload);
    if frameMessage is string {
        return frameMessage;
    }
    return payload.toJsonString();
}

# Iterator that converts OpenAI's Server-Sent Event stream into a stream of
# normalized `ai:ChatCompletionChunk` values. Each `data:` line is parsed into the
# OpenAI wire chunk and mapped via `toAiChunk`; the terminating `[DONE]` sentinel and
# blank lines end or are skipped, and the chat span is closed once the stream is done.
#
# A frame that cannot be parsed is reported as an error rather than skipped: OpenAI emits
# `{"error": {...}}` mid-stream when a generation is cut short, and skipping it would end
# the stream silently, handing the caller a truncated answer that looks complete.
class OpenAiChunkIterator {
    private stream<http:SseEvent, error?> sseStream;
    private observe:ChatSpan span;
    private boolean done = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:ChatSpan span) {
        self.sseStream = sseStream;
        self.span = span;
    }

    public isolated function next() returns record {|ai:ChatCompletionChunk value;|}|ai:Error? {
        if self.isDone() {
            return ();
        }
        while true {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                return self.finish();
            }
            if event is error {
                return self.failStream(error ai:LlmConnectionError("Error while reading the model stream", event));
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == "[DONE]" {
                return self.finish();
            }
            json|error payload = trimmedData.fromJsonString();
            if payload is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Invalid or malformed chunk received from the model", payload));
            }
            string? errorMessage = extractStreamErrorFrame(payload);
            if errorMessage is string {
                return self.failStream(error ai:LlmError(string `Error received mid-stream from the model: ${errorMessage}`));
            }
            CreateChatCompletionStreamResponse|error wireChunk = payload.cloneWithType();
            if wireChunk is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Unexpected chunk shape received from the model", wireChunk));
            }
            ai:ChatCompletionChunk chunk = toAiChunk(wireChunk);
            self.recordChunk(chunk);
            return {value: chunk};
        }
    }

    public isolated function close() returns ai:Error? {
        if !self.markDone() {
            self.span.close();
        }
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    // Records the finish reason and usage the span reports for the completed generation.
    private isolated function recordChunk(ai:ChatCompletionChunk chunk) {
        ai:ChatCompletionChunkChoice[] choices = chunk.choices;
        if choices.length() > 0 {
            ai:FinishReason? finishReason = choices[0].finishReason;
            if finishReason is ai:FinishReason {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
        ai:CompletionTokenUsage? usage = chunk?.usage;
        if usage is ai:CompletionTokenUsage {
            int? promptTokens = usage?.promptTokens;
            if promptTokens is int {
                self.span.addInputTokenCount(promptTokens);
            }
            int? completionTokens = usage?.completionTokens;
            if completionTokens is int {
                self.span.addOutputTokenCount(completionTokens);
            }
        }
    }

    // Ends the stream cleanly, closing the span exactly once.
    private isolated function finish() returns () {
        if !self.markDone() {
            self.span.close();
        }
        return ();
    }

    // Ends the stream with an error, closing the span exactly once.
    private isolated function failStream(ai:Error err) returns ai:Error {
        if !self.markDone() {
            self.span.close(err);
        }
        return err;
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    // Marks the stream as done, returning whether it was already marked before this call.
    private isolated function markDone() returns boolean {
        lock {
            boolean wasDone = self.done;
            self.done = true;
            return wasDone;
        }
    }
}

# Iterator that converts the Responses API SSE stream into a stream of normalized
# `ai:ChatCompletionChunk` values. Text deltas, tool-call starts
# (`response.output_item.added`) and argument fragments
# (`response.function_call_arguments.delta`) are each mapped to a chunk;
# lifecycle/other events are skipped, and the chat span is closed once the stream ends.
#
# As on the Chat Completions path, an unparseable frame is an error rather than a skip.
# `error` events and `response.failed` end the stream with the failure the API reported,
# instead of being handed to the caller as a normal short completion.
class ResponsesChunkIterator {
    private stream<http:SseEvent, error?> sseStream;
    private observe:ChatSpan span;
    private ResponsesStreamState state = {};
    private boolean done = false;

    isolated function init(stream<http:SseEvent, error?> sseStream, observe:ChatSpan span) {
        self.sseStream = sseStream;
        self.span = span;
    }

    public isolated function next() returns record {|ai:ChatCompletionChunk value;|}|ai:Error? {
        if self.isDone() {
            return ();
        }
        while true {
            record {|http:SseEvent value;|}|error? event = self.sseStream.next();
            if event is () {
                return self.finish();
            }
            if event is error {
                return self.failStream(error ai:LlmConnectionError("Error while reading the model stream", event));
            }
            string? data = event.value.data;
            if data is () {
                continue;
            }
            string trimmedData = data.trim();
            if trimmedData == "" {
                continue;
            }
            if trimmedData == "[DONE]" {
                return self.finish();
            }
            json|error payload = trimmedData.fromJsonString();
            if payload is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Invalid or malformed event received from the model", payload));
            }
            ResponsesStreamEvent|error ev = payload.cloneWithType();
            if ev is error {
                return self.failStream(error ai:LlmInvalidResponseError(
                        "Unexpected event shape received from the model", ev));
            }
            if ev.'type == "error" {
                return self.failStream(error ai:LlmError(
                        ev.message ?: "Error event received from the Responses stream"));
            }
            if ev.'type == "response.failed" {
                return self.failStream(error ai:LlmError(responsesFailureMessage(ev)));
            }
            ai:ChatCompletionChunk? chunk = responsesEventToChunk(ev, self.state);
            if chunk is ai:ChatCompletionChunk {
                self.recordChunk(chunk);
                return {value: chunk};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        if !self.markDone() {
            self.span.close();
        }
        error? result = self.sseStream.close();
        if result is error {
            return error ai:LlmConnectionError("Error while closing the model stream", result);
        }
        return ();
    }

    // Records the finish reason and usage the span reports for the completed generation.
    private isolated function recordChunk(ai:ChatCompletionChunk chunk) {
        ai:ChatCompletionChunkChoice[] choices = chunk.choices;
        if choices.length() > 0 {
            ai:FinishReason? finishReason = choices[0].finishReason;
            if finishReason is ai:FinishReason {
                self.span.addFinishReason(finishReason);
                self.span.addOutputType(observe:TEXT);
            }
        }
        ai:CompletionTokenUsage? usage = chunk?.usage;
        if usage is ai:CompletionTokenUsage {
            int? promptTokens = usage?.promptTokens;
            if promptTokens is int {
                self.span.addInputTokenCount(promptTokens);
            }
            int? completionTokens = usage?.completionTokens;
            if completionTokens is int {
                self.span.addOutputTokenCount(completionTokens);
            }
        }
    }

    // Ends the stream cleanly, closing the span exactly once.
    private isolated function finish() returns () {
        if !self.markDone() {
            self.span.close();
        }
        return ();
    }

    // Ends the stream with an error, closing the span exactly once.
    private isolated function failStream(ai:Error err) returns ai:Error {
        if !self.markDone() {
            self.span.close(err);
        }
        return err;
    }

    private isolated function isDone() returns boolean {
        lock {
            return self.done;
        }
    }

    // Marks the stream as done, returning whether it was already marked before this call.
    private isolated function markDone() returns boolean {
        lock {
            boolean wasDone = self.done;
            self.done = true;
            return wasDone;
        }
    }
}

# Builds the string stream behind the dependently-typed `generateStream`. The
# native `StreamGenerator` shim trampolines here so the type gating stays in
# Ballerina. Only `string` is supported; other types yield an error because a
# partial generation is a valid value only for `string`. When valid, the
# underlying `chatStream` chunks are projected onto their text fragments.
#
# + llmModel - The model provider whose `chatStream` supplies the chunks
# + prompt - The prompt to send to the model
# + td - The caller's expected type; must be `string`
# + return - A stream of text fragments, or an error if the type is unsupported
function generateLlmResponseStream(ModelProvider llmModel, ai:Prompt prompt, typedesc<anydata> td)
        returns stream<string, ai:Error?>|ai:Error {
    if td !is typedesc<string> {
        return error ai:Error("This data type is not supported for streaming. " +
            "'generateStream' supports only 'string'; use 'generate' for structured types.");
    }
    stream<ai:ChatCompletionChunk, ai:Error?> chunks = check llmModel->chatStream({role: ai:USER, content: prompt});
    stream<string, ai:Error?> textStream = new (new ChunkTextIterator(chunks));
    return textStream;
}

# Projects a normalized `ai:ChatCompletionChunk` stream onto its text content,
# yielding each non-empty `delta.content` fragment and skipping tool-call and
# usage-only chunks. Backs `generateLlmResponseStream`.
class ChunkTextIterator {
    private stream<ai:ChatCompletionChunk, ai:Error?> chunks;

    isolated function init(stream<ai:ChatCompletionChunk, ai:Error?> chunks) {
        self.chunks = chunks;
    }

    public isolated function next() returns record {|string value;|}|ai:Error? {
        while true {
            record {|ai:ChatCompletionChunk value;|}|ai:Error? next = self.chunks.next();
            if next is () {
                return ();
            }
            if next is ai:Error {
                return next;
            }
            ai:ChatCompletionChunkChoice[] choices = next.value.choices;
            if choices.length() == 0 {
                continue;
            }
            string? content = choices[0].delta.content;
            if content is string && content.length() > 0 {
                return {value: content};
            }
        }
    }

    public isolated function close() returns ai:Error? {
        return self.chunks.close();
    }
}
